### ISSUE TITLE
Migrate to Taskcluster

### ISSUE THREAD

**Issue by aneeshusa** [servo/saltfs#559]
This is a meta issue for the Taskcluster migration.

Initial checklist from our meeting with TC folks at the All Hands (thanks @edunham for taking notes!):

- [ ] Get Pete Moore's help setting up a Windows AMI that meets TaskCluster's needs and has our build deps installed. Some possible options:
    - Snapshotting current builders
    - Creating new AMIs from scratch based on TC deps
    - Salting current builders and building AMIs via Packer
- [x] Create Dockerfile with the Linux build deps using Salt (#706)
- [ ] Verify that Servo's tests can run in a Docker container. The Firefox tests use a loopbback video device mounted to the countainer (xvfb), and we do as well so hopefully not an issue.
- [ ] @Manishearth needs to fix the IPC file fallback thing on Linux, as Firefox has observed that IO is slow on Docker and creating a lot of files might be a problem (but using a ramdisk/tempfs is ok).
- [ ] Port Buildbot yaml steps to Taskcluster decision tasks
- [ ] For Mac, consult Dustin and Wander's work on PuppetAgain (https://github.com/mozilla/build-puppet/tree/master/modules/generic_worker)
- [ ] Consult Balrog repo which auto-builds Docker images and pushes them to Docker Hub so that their image keys can be included in build deps
- [ ] Figure out caching story (for SERVO_HOME and CARGO_HOME)

**Comment by Manishearth** [comment]
A workaround for the IPC thing is to just mount a tempfs on `/tmp`

**Comment by aneeshusa** [comment]
FYI, when we move to Ubuntu 16.04 (#462), I believe systemd will automatically mount a `tmpfs` on `/tmp`, although not sure if that's the case with Docker/TC.

**Comment by Manishearth** [comment]
Okay, that's good. The main problem is that IPC basically assumes that tmpfs is on /tmp and sticks all of its buffers there, and if that turns out not to be the case the fallback to actual files is horrible.

**Comment by aneeshusa** [comment]
A neat trick I just learned is using the Taskcluster indexing service to make it easy to find jobs ([docs here](https://docs.taskcluster.net/reference/core/taskcluster-index/references/api)). For now we can have a static route to be able to see the latest job, but it looks like in the future we'll want to dynamically generate the "route" for each job we submit so our jobs don't all overwrite each other. We can upgrade to dynamic routes once we have a decision task. Shoutout to @staktrace for their pull servo/webrender#1871 where I learned about this!

**Comment by SimonSapin** [comment]
I’ve had a chat with @JohanLorenzo today where I asked a lot of questions about Taskcluster and how it’s being used in Firefox, to get a better idea of what we can or should do for Servo. CC @jdm

## What we have today

Homu is the service that listens for commands such as `@bors-servo r+` in github PR comments, maintains [the queue](http://build.servo.org/homu/queue/servo), creates merge commits, and schedules them for testing and landing into the `master` branch. It is *not* aware of pre-review testing done by some CI services as soon as a PR is opened.

When Homu decides to try and merge a PR it creates a merge commit, pushes it to the `auto` branch, and then waits. It is up to CI services such as Travis-CI, AppVeyor, or Taskcluster to be notified of this push through separate webhooks or integration, start corresponding builds/jobs/tasks, then communicate results by setting github [Statuses](https://developer.github.com/v3/repos/statuses/) on the merge commit. As far as I know there is no web UI on github to view these statuses, since the merge commit is not associated with the PR from github’s point of view.

Homu gets notified of these status changes, reports results to the PR in comments, optionally pushes the merge commit to `master`, and carries on with the next PR in the queue.

Taskcluster has some [github integration](https://docs.taskcluster.net/docs/manual/using/github) based on github events such as pushes. It looks at `.taskcluster.yml` in the repo to schedule a fixed number of tasks with limited interpolation of data from the event in the tasks’ config. As of this writing this intregration is configured on (at least) `servo/servo` and `servo/webrender`, but Homu only looks at the results for WebRender.

## Going further

For doing things more complex than having a fixed set of independent tasks, Firefox starts with a "decision task" which is in charge defining the entire task graph for a given push. It runs arbitrary code that talks to the Taskcluster API, possibly through a library such as [the Python client](https://github.com/taskcluster/taskcluster-client.py).

Creating/scheduling a task through the API returns its ID. "Downstream" tasks can them be created with a dependency on that ID. A tasks only starts running after all of its dependencies succeed (if they do). To avoid running half a dependency graph in case something goes wrong in the middle of the decision task, a trick/pattern is to make every other task depend on the decision task.

Each task can produce a number of [artifacts](https://docs.taskcluster.net/docs/manual/tasks/artifacts): files that are made available over HTTP until their expiration date. The [generic-worker](https://docs.taskcluster.net/docs/reference/workers/generic-worker) and [docker-worker](https://docs.taskcluster.net/docs/reference/workers/docker-worker) worker types both support uploading artifacts through [their config](https://docs.taskcluster.net/docs/reference/workers/docker-worker/docs/payload). Artifacts can be fetched based on the ID of the task that produced it.

Tasks can be associated to a number of "routes". For example, a route could be minted based on the repo name and PR number. This provides ways other than the random-looking IDs to find again a task or an artifact produced by a task.

## Building docker images as needed

Currently, both Servo and WebRender use Taskcluster’s `docker-worker` with docker images hosted on DockerHub. I believe these images were built and uploaded manually. Compare with Firefox which has `Dockerfile`s and other things needed to build images in-tree, and modifying them in the same commit that relies on those modifications [Just Works](https://firefox-source-docs.mozilla.org/taskcluster/taskcluster/docker-images.html). The decision task hashes the files involved in creating an image and uses that hash as the image’s identifier. It looks up a route that includes a hash, to find out if there’s already a task that has create this exact image. If not, it schedules that task. Then downstream tasks that want to use that image can depend on the image-creating task, and obtain the image as a task artifact.

## Caching `$CARGO_HOME`

This is one of the items listed in this issue description. For this I suspect that we can so something similar to what’s described above for Docker images, except that instead of an exact hash we’d have a route like `something.something.{{ platform }}.latest` so that `$CARGO_HOME` is populated from an artifact from the last successful build on the same platform.

## Cron-like jobs

To publish Nightly builds, we can use the [Taskcluster Hooks Service](https://tools.taskcluster.net/hooks) to run tasks periodically, rather than in reaction to github events. See also [how Firefox uses this service](https://firefox-source-docs.mozilla.org/taskcluster/taskcluster/cron.html).

**Comment by aneeshusa** [comment]
@SimonSapin thanks for writing all of that down! Since I originally heard about the Firefox TC setup I've been wanting to get Servo to the same place. Here's my rough idea of a migration plan:
- use Salt to build Docker images from saltfs automatically on TaskCluster on each merge in saltfs
- use those Docker images in the servo repo and move all the Servo builds to TaskCluster, ideally using pinned Docker images
- once everything is on TC, move the saltfs bits into the servo repo, but keep the TC builds separate at first
- once the code is together, rejigger the TC builds in servo so that images are built first, then used in the Servo build
- add decision task logic to only build a new image when necessary

Once all the code lives in Servo, we can also consider moving away from Salt for image builds (depends on the Windows/macOS setup).

We're currently still in step 1; #849 and #855 are the latest PRs.

**Comment by SimonSapin** [comment]
Salt is useful too coordinate remote already-running machines, but it feels redundant when it comes to building a docker image compared to having a few commands like `apt-get` directly in a `Dockerfile`. What does it bring there?

**Comment by SimonSapin** [comment]
> I suspect that we can so something similar to what’s described above for Docker images, except that instead of an exact hash we’d have a route like `something.something.{{ platform }}.latest` so that `$CARGO_HOME` is populated from an artifact from the last successful build on the same platform.

https://docs.taskcluster.net/docs/manual/design/namespaces#docker-worker-caches also mentions “Docker-Worker Caches” which are located on individual worker instances, which might be preferable for something like caching `$CARGO_HOME`.

**Comment by SimonSapin** [comment]
I think https://docs.taskcluster.net/docs/reference/workers/docker-worker/docs/caches is the docs for that feature. It also looks much easier than messing with routes and artifacts.

**Comment by SimonSapin** [comment]
These caches are always read-write, so we’d probably want to disable them for PR builds since code registry cache poisoning could be an attack vector.

**Comment by SimonSapin** [comment]
First PR to land a decision task: https://github.com/servo/servo/pull/21776

**Comment by SimonSapin** [comment]
Moving this to https://github.com/servo/servo/issues/22325
